### ISSUE TITLE
No tag for 0.2.4 and pypi sources do not include tar files

### ISSUE THREAD

**Issue by goanpeca** [alisterburt/dynamotable#2]
Hi @alisterburt, it seems there is no tag for 0.2.4 and pypi sources do not include tar files.

Could you update/create a tag :) ?

Thanks!

**Comment by alisterburt** [comment]
Hi @goanpeca - I pushed a tag for v0.2.4 https://github.com/teamtomo/dynamotable/releases/tag/v0.2.4

Is this enough for you to move forwards?
